my_admin:
    resource: "@MyAdminBundle/Controller/"
    type:     annotation
    prefix:   /my_admin

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /
    
user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
   
user_controller:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user
    
pages_admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin    

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

