my_admin:
    resource: "@MyAdminBundle/Controller/"
    type:     annotation
    prefix:   /my_admin

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
pages:
    resource: "@PagesBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
