# app/config/security.yml
security:
   encoders:
       FOS\UserBundle\Model\UserInterface: sha512

   role_hierarchy:
       ROLE_ETUDIANT:       ROLE_USER
       ROLE_PROFESSEUR:       ROLE_USER
       ROLE_ADMIN:       ROLE_USER
       ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

   providers:
       fos_userbundle:
           id: fos_user.user_provider.username

   firewalls:
       main:
           pattern: ^/
           form_login:
               check_path: /login_check
               login_path: /login
               provider: fos_userbundle
               always_use_default_target_path: false
               default_target_path:            /my_admin/tableau-de-bord.html
               target_path_parameter:          _target_path
               use_referer:                    false
           logout:
                path:       fos_user_security_logout
                target: /
           remember_me:
                key:        %secret%
           logout: true
              # provider: fos_userbundle
              # csrf_provider: form.csrf_provider

           anonymous:    true

   access_control:
       - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
       - { path: ^/admin/, role: ROLE_ADMIN }
       - { path: ^/my_admin/, role: ROLE_USER }
       - { path: ^/etudiant/, role: ROLE_ETUDIANT }
       - { path: ^/professeur/, role: ROLE_PROFESSEUR }
