# Import routing ADMIN
    
# Routing MAIN
my_admin:
    path:     /tableau-de-bord.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:dashboard }
    
my_admin_infos_perso:
    path:     /informations-personnelles/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:infosPerso }
    requirements:
        id: \d+

my_admin_infos_cin:
    path:     /informations-cin/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:infosCin }  
    requirements:
        id: \d+     
    
my_admin_infos_picture:
    path:     /informations-avatar/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:infosPic }  
    requirements:
        id: \d+   
    
my_admin_infos_prof:
    path:     /informations-professeur/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:prof }  
    requirements:
        id: \d+   
    
my_admin_infos_verification:
    path:     /informations-verification.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:verif }    

my_admin_infos_rib:
    path:     /informations-identite-bancaire/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:rib }
    requirements:
        id: \d+   
    
my_admin_infos_compl:
    path:     /informations-complementaires/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:infoComplementaire }
    requirements:
        id: \d+   
        
my_admin_publier_annonce:
    path:     /publier-annonce.html
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:annonce }
    
my_admin_publier_annonce_active:
    path:     /activer-annonce/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:activeAnnonce }
    requirements:
        id: \d+  
    
my_admin_publier_annonce_desactive:
    path:     /desactiver-annonce/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:desactiveAnnonce }
    requirements:
        id: \d+ 
    
my_admin_accepte_demande:
    path:     /accepter-demande/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:acceptDemande }
    requirements:
        id: \d+ 
    
my_admin_refused_demande:
    path:     /refuser-demande/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:refuseDemande }
    requirements:
        id: \d+ 
    
my_admin_archive_message:
    path:     /archiver-message/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:archiveMessage }
    requirements:
        id: \d+ 
    
my_admin_delete_message:
    path:     /supprimer-message/{id}
    methods: [GET|POST]
    defaults: { _controller: MyAdminBundle:MyAdmin:deleteMessage }
    requirements:
        id: \d+ 
    
my_admin_archive:
    path:     /messages-archivees.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:archive }

my_admin_historique_annonces:
    path:     /mes-annonces.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:myannonces }

my_reservations:
    path:     /mes-reservations.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:myreservations }     

my_money:
    path:     /argent.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:money }

my_money_details:
    path:     /details-argent.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:details }
    
my_payment_details:
    path:     /details-paiments.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:payment }
    
my_boite_reception:
    path:     /mes-messages.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:message }
    
avis:
    path:     /avis.html
    methods: [GET]
    defaults: { _controller: MyAdminBundle:MyAdmin:avis }     