<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{    
    /**
     * Get number of signed lease
     * @return number integer of signed lease
     * @access public
     * @version 1.0
     * @author Constant SIDJUI
     * @copyright ©101Cours 2017.
     */
    public function getSearchUsers($data){
        
        // Build query builder
    	$qb = $this->createQueryBuilder('l')
                   ->select('l')
                   ->join('l.cours', 'u')
                   ->join('l.city', 'p')
                   ->where('l.product = :product')
                   ->andWhere('p.statut = :signInfo')
                   ->andWhere('u = :user')
                   ->setParameter('product', 'sign')
                   ->setParameter('signInfo', 'signed_complete')
                   ->setParameter('user', $user);
        
        // Get query
        $query = $qb->getQuery();
    	
    	// Return results
        return $query->getResult();
        
        
        
    }
}
