services:
#    pages.example:
#        class: PagesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.twig_extension:
        class: PagesBundle\Twig\PagesExtension
        public: false
        tags:
            - { name: twig.extension }
