<?php

namespace MyAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CinAttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CinAttachementRepository extends EntityRepository
{
}
