<?php

namespace MyAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends EntityRepository
{
    /**
     * 
     * @param type $city
     * @return type
     */
    public function getAjaxSearch($city){
        // Clean json code
        $keyCity = html_entity_decode(strtolower(trim(htmlentities($city))));
        
        // Build query
        $cities = $this->createQueryBuilder('c')
                       ->select('c.id, c.name, c.postalCode')
                       ->where('c.name LIKE :keyCity OR c.postalCode LIKE :keyCity')
                       ->setParameter('keyCity', $keyCity.'%')
                       ->orderBy('c.name')
                       ->distinct('c.name')
                       ->setMaxResults(10)
                       ->getQuery();
        // Return result
        return $cities->getResult();
    }
}
