<?php

namespace MyAdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingAttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingAttachementRepository extends EntityRepository
{
}
